# Generated by Django 3.2.21 on 2023-09-14 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_on_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='on_sale',
        ),
    ]
